let data=[
      { //butterscotch
        id:"Heavenly-Butterscotch-Cake-Half-Kg",
        name:"Heavenly Butterscotch Cake- Half Kg",
        price:725,
        src: ,
        CakeFlavour:"Butterscotch",
        TypeofCake:"Cream",
        Weight: "Half Kg",
        Shape:"Round",
        Serves:"4-6 People",
        Size:"6 inches in Diameter"
      },
      {
        id:"Butterscotch-Cake-With-Rasmalai-1-kg",
        name:"Butterscotch Cake With Rasmalai 1kg", 
        price:1375,
        src: ,
        CakeFlavour:"Butterscotch With Rasmalai",
        TypeofCake:"Cream",
        Weight:"1 Kg",
        Shape:"Round",
        Serves:"10-12 People",
        Size:"9 inches in Diameter"
      },
      {
        id:"Crunchy-Butterscotch-Cake-Half-Kg",
        name:"Crunchy Butterscotch Cake Half Kg",
        price:575,
        src: ,
        CakeFlavour:"Butterscotch",
        TypeofCake:"Cream",
        Weight:"Half Kg",
        Shape:"Round",
        Serves:"4-6 People",
        Size:"6 inches in Diameter"
      },
      {
        id:"Heart-Shaped-Butterscotch-Cake-Half-Kg",
        name:"Heart Shaped Butterscotch Cake Half Kg",
        price:725,
        src: ,
        CakeFlavour:"Butterscotch",
        TypeofCake:"Cream",
        Weight:"Half Kg",
        Shape:"Heart Shaped",
        Serves:"4-6 People",
        Size:"6 inches in diameter"
      },
      {
        id:"Butterscotch-Bento-Cake-250-Gram",
        name:"Butterscotch Bento Cake 250 Gram",
        price:449,
        src: ,
        Flavour:"Butterscotch",
        Weight:"250 gms",
        TypeofCake:"Cream Cake",
        Shape:"Round",
        CakesVersion:"Contains Egg",
        Serves:"2-3 people"
      },
      {
        id:"Honey-Bee-Butterscotch-Cake-1-Kg",
        name:"Honey Bee Butterscotch Cake 1 Kg",
        price:1375,
        src: ,
        CakeFlavour:"Butterscotch",
        TypeofCake:"Cream",
        Weight:"1 Kg",
        Shape:"Round",
        Serves:"10-12 People",
        Size:"9 inches in Diameter"
      },//chocolate
      {
        id:"Fudge-Brownie-Cake-1-kg",
        name:"Fudge Brownie Cake 1 kg",
        price:1275,
        src: ,
        CakeFlavour:"Truffle",
        Weight:"1 Kg",
        Shape:"Round",
        Serves:"10-12 People",
        Size:"9 inches in Diameter"
      },
      {
        id:"Kit-Kat-Crunch-Cream-Cake-Half-Kg",
        name:"Kit Kat Crunch Cream Cake Half Kg",
        price:675,
        src: ,
        Weight:"Half Kg",
        Flavour:"Kit Kat",
        CakesVersion:"Contains Egg",
        Typeofcake:"Cream cake",
        Shape:"Round",
        Serves:"4:6 people",
        Size:"6 inches (approx)"
      },
      {
        id:"Dark-Chocolate-Cream-Delight-1-Kg",
        name:"Dark Chocolate Cream Delight 1 Kg",
        price:1275,
        src: ,
        Weight:"1 Kg",
        Flavour:"Chocolate Cream",
        CakesVersion:"Contains Egg",
        Typeofcake:"Cream cake",
        Shape:"Round",
        Serves:"10:12 people",
        Size:"9 inches (approx)"
      },
      {
        id:"Chocolate-Caramel-Fudge-Cake-2-Kg",
        name:"Chocolate Caramel Fudge Cake 2 Kg",
        price:2325,
        src: "",
        CakeFlavour:"Caramel", 
        TypeofCake:"Cream Cake",
        Weight:"2 Kg",
        Shape:"Round",
        Serves:"20-24 People",
        Size:"12 Inches in Diameter"
      },
      {
        id:"Creamy-Chocolate-Dream-Cake-Half-Kg",
        name:"Creamy Chocolate Dream Cake Half Kg",
        price:675,
        src: "",
        Weight:"Half Kg",
        Flavour:"Chocolate Cream",
        CakesVersion:"Contains Egg",
        Typeofcake:"Cream cake",
        Shape:"Round",
        Serves:"4:6 people",
        Size:"6 inches (approx)"
      },
      {
        id:"Delicious-Heart-Shaped-Chocolate-Cake-1-Kg",
        name:"Delicious Heart Shaped Chocolate Cake 1 Kg",
        price:1375,
        src: "",
        CakeFlavour:"Chocola",
        TypeOfCake:"Cream",
        Weight:"1 Kg",
        CakeShape:"Heart Shaped",
        Serves:"10-12 People",
        Size:"9 inches in Diameter"
      },//pineapple
      {
        id:"Happy-Emoji-Pineapple-Cake-Eggless-Half-Kg",
        name:"Happy Emoji Pineapple Cake Eggless Half Kg",
        price:625,
        src: "",
        CakeFlavour:"Pineapple",
        Version:"Eggless",
        Typeofcake:"Cream",
        Weight:"Half Kg",
        Shape:"Round",
        Serves:"4-6 People",
        Size:"6 Inches in Diameter"
      },
      {
        id:"Tropical-Bliss-Pineapple-Bento-250-Gram",
        name:"Tropical Bliss Pineapple Bento 250 Gram",
        price:449,
        src: "",
        Flavour:"Pineapple",
        Weight:"250 gms",
        TypeofCake:"Cream Cake",
        Shape:"Round",
        CakesVersion:"Contains Egg",
        Serves:"2-3 people"
      },
      {
        id:"Roses-On-Top-Pineapple-Designer-Cake-Half-Kg-Eggless",
        name:"Roses On Top Pineapple Designer Cake Half Kg Eggless",
        price:725,
        src: "",
        CakeFlavour:"Pineapple",
        Version:"Eggless",
        TypeofCake:"Cream",
        Shape:"Round",
        Weight:"Half Kg",
        Serves:"4-6 People",
        Size:"6 Inches In Diameter"
      },
      {
        id:"Pink-Pineapple-Cream-Cake-1-Kg-Eggless",
        name:"Pink Pineapple Cream Cake 1 Kg Eggless",
        price:1375,
        src:"",
        CakeFlavour:"Pineapple",
        Version:"Eggless",
        TypeofCake:"Cream Cake",
        Weight:"1 Kg",
        Shape:"Round",
        Serves:"10-12 People",
        Size:"9 Inches in Diameter"
      },
      {
        id:"Delicious-Pineapple-Cake-Half-Kg-Eggless",
        name:"Delicious Pineapple Cake Half Kg Eggless",
        price:625,
        src:"",
        CakeFlavour:"Pineapple",
        Version:"Eggless",
        TypeofCake:"Cream",
        Weight:"Half Kg",
        Shape:"Round",
        Serves:"4-6 People",
        Size:"6 inches in Diameter"
      },
      {
        id:"Pineapple-With-Butterscotch-Cake-Eggless-2-Kg",
        name:"Pineapple With Butterscotch Cake Eggless 2 Kg",
        price:2675,
        src:"",
        CakeFlavour:"Pineapple With Butterscotch",
        Version:"Eggless",
        TypeofCake:"Cream",
        Weight:"2 Kg",
        Shape:"Round",
        Serves:"20-24 People",
        Size:"12 inches in Diameter",
        CountryofOrigin:"India"
      },//Vanila cakes
      {
        id:"Fresh-Vanilla-Cake-1-Kg",
        name:"Fresh Vanilla Cake 1 Kg",
        price:1099,
        src:"",
        CakeFlavour:"Vanilla",
        TypeofCake:"Cream",
        Weight:"1 Kg",
        Shape:"Round",
        Serves:"10-12 People",
        Size:"9 inches in Diameter"
      },
      {
        id:"Vanilla-Bliss-in-Pink-1-Kg",
        name:"Vanilla Bliss in Pink 1 Kg",
        price:1175,
        src:"",
        Weight:"1 Kg",
        Flavour:"Vanilla",
        Cakeversion:"Contains egg",
        Typeofcake:"Cream cake",
        Shape:"Half cake",
        Serves:"10:12 people"
      },
      {
        id:"Luscious-Vanilla-Cake-Half-Kg",
        name:"Luscious Vanilla Cake Half Kg",
        price:625,
        src:"",
        Weight:"Half Kg",
        Flavour:"Vanilla",
        Cakeversion:"Contains egg",
        Typeofcake:"Cream cake",
        Shape:"Half cake",
        Serves:"4:6 people"
      },
      {
        id:"Rose-Fondant-Cake-Vanilla-5-kg",
        name:"Rose Fondant Cake Vanilla 5 kg",
        price:9425,
        src:"",
        CakeFlavour:"Vanilla",
        Weight:"5kg",
        TypeofCake:"Fondant",
        Shape:"Round",
        CountryofOrigin:"India"
      },
      {
        id:"Flamboyant-Barbie-Cake-Vanilla-3-kg",
        name:"Flamboyant Barbie Cake Vanilla 3 kg",
        price:4025,
        src:"",
        CakeFlavour:"Vanilla",
        Typeofcake:"Cream",
        Weight:"3 Kg",
        Shape:"Doll Shaped",
        Serves:"30-36 People",
        Size:"12 inches in Diameter"
      },
      {
        id:"Blue-Shirt-Fondant-Cake-3kg-Vanilla",
        name:"Blue Shirt Fondant Cake 3kg Vanilla",
        price:5225,
        src:"",
        CakeFlavour:"Vanilla",
        TypeofCake:"Fondant",
        Weight:"3 Kg",
        Shape:"Round",
        Serves:"30-36 People",
        Size:"12 inches in Diameter"
      },//Fresh Fruits cakes
      {
        id:"Fresh-Fruit-Vanilla-Cake-1-Kg",
        name:"Fresh Fruit Vanilla Cake 1 Kg",
        price:1575,
        src:"",
        CakeFlavour:"Fresh Fruit Vanilla",
        TypeofCake:"Cream",
        Weight:"1 Kg",
        Shape:"Round",
        Serves:"10-12 People",
        Size:"9 inches in Diameter"
      },
      {
        id:"Fruit-Fantasy-Cake",
        name:"Fruit Fantasy Cake",
        price:2275,
        src:"",
        Typeofcake:"Cream cake",
        Flavour:"Mix fruit",
        Weight:"2 Kg",
        Shape:"Round",
        Serves:"20-24 people",
        Size:"12 inches (approx)",
        Cakesversion:"Eggless"
      },
      {
        id:"Fruit-Chocolate-Cake-1-kg",
        name:"Fruit Chocolate Cake 1 kg",
        price:1575,
        src:"",
        CakeFlavour:"Chocolate",
        TypeofCake :"Cream",
        Weight:"1 Kg",
        Shape:"Round",
        Serves:"10-12 People",
        Size:"9 inches in Diameter"
      },
      {
        id:"Fresh-Vanilla-Cake-1-Kg",
        name:"Fresh Vanilla Cake 1 Kg",
        price:1099,
        src:,
        CakeFlavour:"Vanilla",
        TypeofCake:"Cream",
        Weight:"1 Kg",
        Shape:"Round",
        Serves:"10-12 People",
        Size:"9 inches in Diameter"
      },
      {
        id:"Fruit-Carnival-Cake-For-Diwali-3-Kg",
        name:"Fruit Carnival Cake For Diwali 3 Kg",
        price:2425,
        src:,
        Flavour:"Mix fruit",
        Weight:"3Kg",
        Cakeversion:"Contains egg",
        Typeofcake:"Cream cake",
        Shape:"Round",
        Serves:"30-36 people",
        Size:"15 inches (approx)"
      },
      {
        id:"Creamy-Vanilla-Fruit-Cake-1-Kg",
        name:"Creamy Vanilla Fruit Cake 1 Kg",
        price:1575,
        src:"",
        CakeFlavour:"Vanilla",
        TypeofCake:"Cream",
        Weight:"1 Kg",
        Shape:"Round",
        Serves:"10-12 People",
        Size:"9 inches in Diameter"
      },//Red Valvet cakes
      {
        id:"Red-Velvet-Celebration-Cake",
        name:"Red Velvet Celebration Cake",
        price:2325,
        src:"",
        Typeofcake:"Cream cake",
        Weight:"2 Kg",
        Shape:"Round",
        Flavour:"Red velvet",
        Serves:"20-24 people",
        Cakesversion: "Contains egg",
        Size:"12 inches (approx)"
      },
      {
        id:"Royal-Red-Velvet-Cake",
        name:"Royal Red Velvet Cake",
        price:725,
        src:"",
        Flavour:"Red velvet",
        Weight:"500 gms",
        TypeofCake:"Cream Cake",
        Shape:"Round",
        CakesVersion:"Contains Egg",
        Serves:"5-6 people"
      },
      {
        id:"Red-Velvet-Gems-Cake-Half-Kg",
        name:"Red Velvet Gems Cake Half Kg",
        price:875,
        src:"",
        CakeFlavour:"Red Velvet",
        TypeofCake:"Cream",
        Weight:"Half Kg",
        Shape:"Round",
        Serves:"4-6 People",
        Size:"6 inches in Diameter"
      },
      {
        id:"Red-Velvet-Heart-Cake-1.5-kg",
        name:"Red Velvet Heart Cake 1.5 kg",
        price:2275,
        src:"",
        CakeFlavour:"Red Velvet",
        TypeofCake:"Cream",
        Weight:"1.5 Kg",
        Shape:"Heart Shaped",
        Serves:"15-18 People",
        Size:"12 inches in Diameter"
      },
      {
        id:"Scrumptious-Red-Velvet-Cake-2-Kg",
        name:"Scrumptious Red Velvet Cake 2 Kg",
        price:3275,
        src:"",
        CakeFlavour:"Red Velvet",
        TypeofCake:"Cream",
        Weight:"2 Kg",
        Shape:"Round",
        Serves:"20-24 People",
        Size:"12 inches in Diameter"
      },
      {
        id:"Red-Velvet-Heart-Cream-Cake-1-Kg",
        name:"Red Velvet Heart Cream Cake 1 Kg",
        price:1474,
        src:"",
        CakeFlavour:"Red Velvet",
        TypeofCake:"Cream",
        Weight:"1 Kg",
        Shape:"Heart",
        Serves:"10-12 People",
        Size:"9 inches in Diameter"
      },//Truffle cakes
      {
        id:"Truffle-Dream-Cake",
        name:"Truffle Dream Cake",
        price:725,
        src:"",
        Typeofcake:"Cream cake",
        Weight:"Half kg",
        Shape:"Round",
        Flavour:"Truffle",
        Serves:"4-6 people",
        Cakesversion:"Contains egg",
        Size:"6 inches (approx)"
      },//1
      {
        id:"Velvet-Truffle-Cake",
        name:"Velvet Truffle Cake",
        price:725,
        src:"",
        Flavour:"Truffle",
        Weight:"500 gms",
        TypeofCake:"Cream Cake",
        Shape:"Round",
        CakesVersion:"Contains Egg",
        Serves:"5-6 people"
      },//2
      {
        id:"Glistening-Truffle-Cake-2-KG",
        name:"Glistening Truffle Cake 2 KG",
        price:2675,
        src:"",
        CakeFlavour:"Truffle",
        Weight:"2 Kg",
        Shape:"Round",
        Serves:"20-24 People",
        Size:"12 inches in Diameter"
      },//3
      {
        id:"Chocolaty-Truffle-Cake-1.5-Kg",
        name:"Chocolaty Truffle Cake 1.5 Kg",
        price:1575,
        src:,
        CakeFlavour:"Chocolate",
        TypeofCake:"Cream",
        Weight:"1.5 Kg",
        Shape:"Round",
        Serves:"15-18 People",
        Size:"12 inches in Diameter"
      },//4
      {
        id:"Whimsical-Truffle-Temptation",
        name:"Whimsical Truffle Temptation",
        price:5225,
        src:"",
        Typeofcake:"Fondant",
        Flavour:"Truffle",
        Weight:"3 Kg",
        Serves:"30-36 people",
        Cakeversion:"Contains egg"
      },//5
      {
        id:"Creamy-Truffle-Cake-1-Kg",
        name:"Creamy Truffle Cake 1 Kg",
        price:1375,
        src:"",
        Weight:"1 Kg",
        Flavour:"Truffle",
        CakesVersion:"Contains Egg",
        Typeofcake:"Cream cake",
        Shape:"Round",
        Serves:"10:12 people",
        Size:"9 inches (approx)"
      },//6
]